package com.uxz.cu.questioncard.dao;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

import com.uxz.cu.questioncard.domain.Questioncard;
import com.uxz.cu.questioncard.domain.QuestioncardExample;
@Mapper
public interface QuestioncardMapper {
	
	/**
	 * 查询课程下的答题卡列表
	 * @param course_id
	 * @return
	 */
	@Select("select * from cu_questioncard where course_id=#{course_id}")
	public List<Questioncard> queryQuestioncardList(String course_id);
	
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cu_questioncard
     *
     * @mbggenerated
     */
    int countByExample(QuestioncardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cu_questioncard
     *
     * @mbggenerated
     */
    int deleteByExample(QuestioncardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cu_questioncard
     *
     * @mbggenerated
     */
    int insert(Questioncard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cu_questioncard
     *
     * @mbggenerated
     */
    int insertSelective(Questioncard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cu_questioncard
     *
     * @mbggenerated
     */
    List<Questioncard> selectByExample(QuestioncardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cu_questioncard
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Questioncard record, @Param("example") QuestioncardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cu_questioncard
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Questioncard record, @Param("example") QuestioncardExample example);
}