package com.uxz.cu.course.domain;

import java.util.Date;

public class Course {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cu_course.course_id
     *
     * @mbggenerated
     */
    private String courseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cu_course.course_name
     *
     * @mbggenerated
     */
    private String courseName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cu_course.category_id
     *
     * @mbggenerated
     */
    private String categoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cu_course.level
     *
     * @mbggenerated
     */
    private String level;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cu_course.memo
     *
     * @mbggenerated
     */
    private String memo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cu_course.imgsrc
     *
     * @mbggenerated
     */
    private String imgsrc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cu_course.creationtime
     *
     * @mbggenerated
     */
    private Date creationtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cu_course.ts
     *
     * @mbggenerated
     */
    private Date ts;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cu_course.course_id
     *
     * @return the value of cu_course.course_id
     *
     * @mbggenerated
     */
    public String getCourseId() {
        return courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cu_course.course_id
     *
     * @param courseId the value for cu_course.course_id
     *
     * @mbggenerated
     */
    public void setCourseId(String courseId) {
        this.courseId = courseId == null ? null : courseId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cu_course.course_name
     *
     * @return the value of cu_course.course_name
     *
     * @mbggenerated
     */
    public String getCourseName() {
        return courseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cu_course.course_name
     *
     * @param courseName the value for cu_course.course_name
     *
     * @mbggenerated
     */
    public void setCourseName(String courseName) {
        this.courseName = courseName == null ? null : courseName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cu_course.category_id
     *
     * @return the value of cu_course.category_id
     *
     * @mbggenerated
     */
    public String getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cu_course.category_id
     *
     * @param categoryId the value for cu_course.category_id
     *
     * @mbggenerated
     */
    public void setCategoryId(String categoryId) {
        this.categoryId = categoryId == null ? null : categoryId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cu_course.level
     *
     * @return the value of cu_course.level
     *
     * @mbggenerated
     */
    public String getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cu_course.level
     *
     * @param level the value for cu_course.level
     *
     * @mbggenerated
     */
    public void setLevel(String level) {
        this.level = level == null ? null : level.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cu_course.memo
     *
     * @return the value of cu_course.memo
     *
     * @mbggenerated
     */
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cu_course.memo
     *
     * @param memo the value for cu_course.memo
     *
     * @mbggenerated
     */
    public void setMemo(String memo) {
        this.memo = memo == null ? null : memo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cu_course.imgsrc
     *
     * @return the value of cu_course.imgsrc
     *
     * @mbggenerated
     */
    public String getImgsrc() {
        return imgsrc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cu_course.imgsrc
     *
     * @param imgsrc the value for cu_course.imgsrc
     *
     * @mbggenerated
     */
    public void setImgsrc(String imgsrc) {
        this.imgsrc = imgsrc == null ? null : imgsrc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cu_course.creationtime
     *
     * @return the value of cu_course.creationtime
     *
     * @mbggenerated
     */
    public Date getCreationtime() {
        return creationtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cu_course.creationtime
     *
     * @param creationtime the value for cu_course.creationtime
     *
     * @mbggenerated
     */
    public void setCreationtime(Date creationtime) {
        this.creationtime = creationtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cu_course.ts
     *
     * @return the value of cu_course.ts
     *
     * @mbggenerated
     */
    public Date getTs() {
        return ts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cu_course.ts
     *
     * @param ts the value for cu_course.ts
     *
     * @mbggenerated
     */
    public void setTs(Date ts) {
        this.ts = ts;
    }
}